#!/bin/bash

# Set the date
DATE=$(date +"%m-%d-%Y")

# Push Files
adb push ~/Documents/buildstuff/GAPPS.zip /sdcard/
adb push ~/android/out/target/product/inc/kernel_$DATE.zip /sdcard/
adb push ~/android/out/target/product/inc/rom_$DATE.zip /sdcard/

# Reboot to recovery
adb reboot recovery
