#!/bin/bash

#cd to AOSP
cd ~/android/

#common sense
make clean

#prepare for build
. build/envsetup.sh

#lunch build
lunch full_inc-userdebug

#build rom
make -j`grep 'processor' /proc/cpuinfo | wc -l`

# Set the date
DATE=$(date +"%m-%d-%Y")

#obviously
exit



